### ISSUE TITLE
font directory

### ISSUE THREAD

**Issue by lilyrxj** [GPUOpen-Tools/radeon_memory_visualizer#12]
Hi sir or Madam,
When I compiled  my code on linux, the following mistakes appeared. I wonder if your package has a font package. or how I should deal with this problem.
QFontDatabase: Cannot find font directory /root/r30023245/radeon_memory_visualizer-master/build/linux/release/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.

Best,
Lily

**Comment by ahosier** [comment]
Hi Lily,

Thank you for your interest in RMV. You may be able to use a slightly older package of Qt (we used to compile with the 5.12.6 package without any issues). I'm assuming you're using Ubuntu, since that's the version we support. If that doesn't work, entering something along the lines of "QFontDatabase: Cannot find font directory" into a search engine may provide a solution. Hope this helps.

Thanks,
Tony.
